### ISSUE TITLE
Tag the release without prefixed v in the release number

### ISSUE THREAD

**Issue by gq1** [sanger-tol/curationpretext#21]
### Description of feature

Currently you have your first pre-release 
https://github.com/sanger-tol/curationpretext/tree/v0.1.0

Can you re-tag it with `0.1.0` without `v`?  Otherwise it will have double v in the pipeline website.

**Comment by DLBPointon** [comment]
Sorry, only just seen the issue.

I've updated the tag to 0.1.0
