### ISSUE TITLE
Zenodo Addition

### ISSUE THREAD

**Issue by DLBPointon** [sanger-tol/curationpretext#23]
### Description of feature

Now that we are on the cusp of a v1 we need to get Zenodo ready. @muffato can you get the zenodo side of this done, as I lack the permissions? I will then go through the docs and add it in.

Thanks

**Comment by muffato** [comment]
Hi Damon. As far as I can tell, I've set up the Zenodo linking
<img width="943" alt="Screenshot 2024-07-08 at 17 24 22" src="https://github.com/sanger-tol/curationpretext/assets/623458/a8dfcf0e-c87a-4a23-ae87-863ea5245ca8">

but we can't get the DOI until after the release. The nf-core guidelines also say that we do the 1.0 release and _then_ get the DOI and add it to the `main` branch of the repository.

Alternatively, if you absolutely want the DOI to be fully embedded in the 1.0 release, I propose you publish a `1.0.0-rc.1` release, then we get the DOI and embed it for an immediate `1.0.0` release.
