### ISSUE TITLE
Install bug: FileNotFound singularity image

### ISSUE THREAD

**Issue by SamCT** [sanger-tol/curationpretext#33]
### Description of the bug

Hello, 

Following the instructions: https://pipelines.tol.sanger.ac.uk/curationpretext/1.0.0/usage , I am getting a FileNotFound error in the most recent version of this pipeline. I successfully installed and ran tests on the sanger-tol/treeval pipeline but am keen to get this running for standardizing curation in our lab.

Thanks,
Sam

### Command used and terminal output
``` nextflow run . -profile test,singularity```
```console
Jul-29 08:00:04.718 [Actor Thread 126] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=SANGERTOL_CURATIONPRETEXT_ALL_FILES:CURATIONPRETEXT_ALLF:ACCESSORY_FILES:TELO_FINDER:FIND_TELOMERE_REGIONS; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Jul-29 08:00:04.737 [Actor Thread 108] ERROR nextflow.processor.TaskProcessor - Error executing process > 'SANGERTOL_CURATIONPRETEXT_ALL_FILES:CURATIONPRETEXT_ALLF:ACCESSORY_FILES:REPEAT_DENSITY:WINDOWMASKER_MKCOUNTS (1)'

Caused by:
  java.io.FileNotFoundException: /local/cluster/singularity-images/nxf/.depot.galaxyproject.org-singularity-blast-2.14.0--h7d5a4b4_1.img.lock (Permission denied)
```

**Comment by DLBPointon** [comment]
Hi @SamCT 

Apologies for the lack of reply, I haven't been getting any notifications from this repo.

We have seen this a few times, we think this is where the pipeline tries to download many containers at the same time and messes up 1 or 2 of them.

In this case, I would suggest cleaning out your singularity cache and then running this first:
```
nf-core download sanger-tol/curationpretext --revision 1.0.0 --compress none -d --force --outdir sanger-curationpretext --container-cache-utilisation amend --container-system singularity
```

This runs the download and translation of containers as a separate step. You should then be able to run the pipeline and be fine.

Again, apologies for not getting back to you sooner.

**Comment by DLBPointon** [comment]
Hi @SamCT 
I'm going to close this issue now, if you need help then feel free to reopen.
